import 'package:flutter/material.dart';

final ThemeData themeLight = ThemeData(
  floatingActionButtonTheme: const FloatingActionButtonThemeData(
    backgroundColor: Color(0xffff0000),
    foregroundColor: Color(0xffffffff),
  ),
  primarySwatch: const MaterialColor(4294901760, {
    50: Color(0xffffe5e5),
    100: Color(0xffffcccc),
    200: Color(0xffff9999),
    300: Color(0xffff6666),
    400: Color(0xffff3333),
    500: Color(0xffff0000),
    600: Color(0xffcc0000),
    700: Color(0xff990000),
    800: Color(0xff660000),
    900: Color(0xff330000)
  }),
  brightness: Brightness.light,
  primaryColor: const Color(0xffff0000),
  primaryColorBrightness: Brightness.dark,
  primaryColorLight: const Color(0xffffcccc),
  primaryColorDark: const Color(0xff990000),
  canvasColor: const Color(0xfffafafa),
  scaffoldBackgroundColor: const Color(0xfffafafa),
  bottomAppBarColor: const Color(0xffffffff),
  cardColor: const Color(0xffffffff),
  dividerColor: const Color(0x1f000000),
  highlightColor: const Color(0x66bcbcbc),
  splashColor: const Color(0x66c8c8c8),
  selectedRowColor: const Color(0xfff5f5f5),
  unselectedWidgetColor: const Color(0x8a000000),
  disabledColor: const Color(0x61000000),
  toggleableActiveColor: const Color(0xffcc0000),
  secondaryHeaderColor: const Color(0xffffe5e5),
  backgroundColor: const Color(0xffff9999),
  dialogBackgroundColor: const Color(0xffffffff),
  indicatorColor: const Color(0xffff0000),
  hintColor: const Color(0x8a000000),
  errorColor: const Color(0xffd32f2f),
  buttonTheme: const ButtonThemeData(
    textTheme: ButtonTextTheme.normal,
    minWidth: 88,
    height: 36,
    padding: EdgeInsets.only(top: 0, bottom: 0, left: 16, right: 16),
    shape: StadiumBorder(
        side: BorderSide(
      color: Color(0xff000000),
      width: 0,
      style: BorderStyle.none,
    )),
    alignedDropdown: false,
    buttonColor: Color(0xffe0e0e0),
    disabledColor: Color(0x61000000),
    highlightColor: Color(0x29000000),
    splashColor: Color(0x1f000000),
    focusColor: Color(0x1f000000),
    hoverColor: Color(0x0a000000),
    colorScheme: ColorScheme(
      primary: Color(0xffff0000),
      primaryVariant: Color(0xff990000),
      secondary: Color(0xffff0000),
      secondaryVariant: Color(0xff990000),
      surface: Color(0xffffffff),
      background: Color(0xffff9999),
      error: Color(0xffd32f2f),
      onPrimary: Color(0xffffffff),
      onSecondary: Color(0xffffffff),
      onSurface: Color(0xff000000),
      onBackground: Color(0xffffffff),
      onError: Color(0xffffffff),
      brightness: Brightness.light,
    ),
  ),
  textTheme: const TextTheme(
    headline1: TextStyle(color: Color(0x8a000000), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    headline2: TextStyle(color: Color(0x8a000000), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    headline3: TextStyle(color: Color(0x8a000000), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    headline4: TextStyle(color: Color(0x8a000000), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    headline5: TextStyle(color: Color(0xdd000000), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    headline6: TextStyle(color: Color(0xdd000000), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    subtitle1: TextStyle(color: Color(0xdd000000), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    bodyText1: TextStyle(color: Color(0xdd000000), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    bodyText2: TextStyle(color: Color(0xdd000000), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    caption: TextStyle(color: Color(0x8a000000), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    button: TextStyle(color: Color(0xdd000000), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    subtitle2: TextStyle(color: Color(0xff000000), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    overline: TextStyle(color: Color(0xff000000), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
  ),
  primaryTextTheme: const TextTheme(
    headline1: TextStyle(color: Color(0xb3ffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    headline2: TextStyle(color: Color(0xb3ffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    headline3: TextStyle(color: Color(0xb3ffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    headline4: TextStyle(color: Color(0xb3ffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    headline5: TextStyle(color: Color(0xffffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    headline6: TextStyle(color: Color(0xffffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    subtitle1: TextStyle(color: Color(0xffffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    bodyText1: TextStyle(color: Color(0xffffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    bodyText2: TextStyle(color: Color(0xffffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    caption: TextStyle(color: Color(0xb3ffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    button: TextStyle(color: Color(0xffffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    subtitle2: TextStyle(color: Color(0xffffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    overline: TextStyle(color: Color(0xffffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
  ),
  inputDecorationTheme: InputDecorationTheme(
    labelStyle: const TextStyle(color: Color(0xdd000000), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    helperStyle: const TextStyle(color: Color(0xdd000000), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    hintStyle: const TextStyle(color: Color(0xdd000000), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    errorStyle: const TextStyle(color: Color(0xdd000000), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    errorMaxLines: null,
    isDense: false,
    contentPadding: const EdgeInsets.only(top: 12, bottom: 12, left: 12, right: 12),
    isCollapsed: false,
    prefixStyle: const TextStyle(color: Color(0xdd000000), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    suffixStyle: const TextStyle(color: Color(0xdd000000), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    counterStyle: const TextStyle(color: Color(0xdd000000), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    filled: true,
    fillColor: const Color(0xFFf2f2f2),
    floatingLabelBehavior: FloatingLabelBehavior.auto,
    errorBorder: OutlineInputBorder(
      borderRadius: BorderRadius.circular(30),
      borderSide: BorderSide(width: 1, color: Colors.grey.shade300, style: BorderStyle.solid),
    ),
    focusedBorder: OutlineInputBorder(
      borderRadius: BorderRadius.circular(30),
      borderSide: BorderSide(width: 1, color: Colors.grey.shade300, style: BorderStyle.solid),
    ),
    focusedErrorBorder: OutlineInputBorder(
      borderRadius: BorderRadius.circular(30),
      borderSide: BorderSide(width: 1, color: Colors.grey.shade300, style: BorderStyle.solid),
    ),
    disabledBorder: OutlineInputBorder(
      borderRadius: BorderRadius.circular(30),
      borderSide: BorderSide(width: 1, color: Colors.grey.shade300, style: BorderStyle.solid),
    ),
    enabledBorder: OutlineInputBorder(
      borderRadius: BorderRadius.circular(30),
      borderSide: BorderSide(width: 1, color: Colors.grey.shade300, style: BorderStyle.solid),
    ),
    border: OutlineInputBorder(
      borderRadius: BorderRadius.circular(30),
      borderSide: BorderSide(width: 1, color: Colors.grey.shade300, style: BorderStyle.solid),
    ),
  ),
  iconTheme: const IconThemeData(color: Color(0xdd000000), opacity: 1, size: 20),
  primaryIconTheme: const IconThemeData(color: Color(0xffffffff), opacity: 1, size: 20),
  sliderTheme: const SliderThemeData(
    activeTrackColor: null,
    inactiveTrackColor: null,
    disabledActiveTrackColor: null,
    disabledInactiveTrackColor: null,
    activeTickMarkColor: null,
    inactiveTickMarkColor: null,
    disabledActiveTickMarkColor: null,
    disabledInactiveTickMarkColor: null,
    thumbColor: null,
    disabledThumbColor: null,
    thumbShape: null,
    overlayColor: null,
    valueIndicatorColor: null,
    valueIndicatorShape: null,
    showValueIndicator: ShowValueIndicator.always,
    valueIndicatorTextStyle: TextStyle(color: Color(0xffffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
  ),
  tabBarTheme: const TabBarTheme(
    indicatorSize: TabBarIndicatorSize.label,
    labelColor: Color(0xffffffff),
    unselectedLabelColor: Color(0xb2ffffff),
  ),
  chipTheme: const ChipThemeData(
    backgroundColor: Color(0x1f000000),
    brightness: Brightness.light,
    deleteIconColor: Color(0xde000000),
    disabledColor: Color(0x0c000000),
    labelPadding: EdgeInsets.only(top: 0, bottom: 0, left: 8, right: 8),
    labelStyle: TextStyle(color: Color(0xde000000), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    padding: EdgeInsets.only(top: 4, bottom: 4, left: 4, right: 4),
    secondaryLabelStyle: TextStyle(color: Color(0x3d000000), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    secondarySelectedColor: Color(0x3dff0000),
    selectedColor: Color(0x3d000000),
    shape: StadiumBorder(
        side: BorderSide(
      color: Color(0xff000000),
      width: 0,
      style: BorderStyle.none,
    )),
  ),
  dialogTheme: const DialogTheme(
      shape: RoundedRectangleBorder(
    side: BorderSide(
      color: Color(0xff000000),
      width: 0,
      style: BorderStyle.none,
    ),
    borderRadius: BorderRadius.all(Radius.circular(0.0)),
  )),
  textSelectionTheme: const TextSelectionThemeData(
    cursorColor: Color(0xffff0000),
    selectionColor: Color(0xffff9999),
    selectionHandleColor: Color(0xffff6666),
  ),
);
