import 'package:flutter/material.dart';

final themeDark = ThemeData(
  floatingActionButtonTheme: const FloatingActionButtonThemeData(
    backgroundColor: Color(0xff000000),
    foregroundColor: Color(0xffffffff),
  ),
  primarySwatch: const MaterialColor(4294901760, {
    50: Color(0xfff2f2f2),
    100: Color(0xffe6e6e6),
    200: Color(0xffcccccc),
    300: Color(0xffb3b3b3),
    400: Color(0xff999999),
    500: Color(0xff808080),
    600: Color(0xff666666),
    700: Color(0xff4d4d4d),
    800: Color(0xff333333),
    900: Color(0xff191919)
  }),
  brightness: Brightness.dark,
  primaryColor: const Color(0xff212121),
  primaryColorBrightness: Brightness.dark,
  primaryColorLight: const Color(0xff9e9e9e),
  primaryColorDark: const Color(0xff000000),
  canvasColor: const Color(0xff303030),
  scaffoldBackgroundColor: const Color(0xff303030),
  bottomAppBarColor: const Color(0xff424242),
  cardColor: const Color(0xff424242),
  dividerColor: const Color(0x1fffffff),
  highlightColor: const Color(0x40cccccc),
  splashColor: const Color(0x40cccccc),
  selectedRowColor: const Color(0xfff5f5f5),
  unselectedWidgetColor: const Color(0xb3ffffff),
  disabledColor: const Color(0x62ffffff),
  toggleableActiveColor: const Color(0xffff0000),
  secondaryHeaderColor: const Color(0xff616161),
  backgroundColor: const Color(0xff616161),
  dialogBackgroundColor: const Color(0xff424242),
  indicatorColor: const Color(0xffff0000),
  hintColor: const Color(0x80ffffff),
  errorColor: const Color(0xffd32f2f),
  buttonTheme: const ButtonThemeData(
    textTheme: ButtonTextTheme.normal,
    minWidth: 88,
    height: 36,
    padding: EdgeInsets.only(top: 0, bottom: 0, left: 16, right: 16),
    shape: StadiumBorder(
        side: BorderSide(
      color: Color(0xff000000),
      width: 0,
      style: BorderStyle.none,
    )),
    alignedDropdown: false,
    buttonColor: Color(0xffcc0000),
    disabledColor: Color(0x61ffffff),
    highlightColor: Color(0x29ffffff),
    splashColor: Color(0xff8c0000),
    focusColor: Color(0x1fffffff),
    hoverColor: Color(0x0affffff),
    colorScheme: ColorScheme(
      primary: Color(0xffff0000),
      primaryVariant: Color(0xff000000),
      secondary: Color(0xffff0000),
      secondaryVariant: Color(0xff990000),
      surface: Color(0xff424242),
      background: Color(0xff616161),
      error: Color(0xffd32f2f),
      onPrimary: Color(0xffffffff),
      onSecondary: Color(0xff000000),
      onSurface: Color(0xffffffff),
      onBackground: Color(0xffffffff),
      onError: Color(0xff000000),
      brightness: Brightness.dark,
    ),
  ),
  textTheme: const TextTheme(
    headline1: TextStyle(color: Color(0xb3ffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    headline2: TextStyle(color: Color(0xb3ffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    headline3: TextStyle(color: Color(0xb3ffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    headline4: TextStyle(color: Color(0xb3ffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    headline5: TextStyle(color: Color(0xffffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    headline6: TextStyle(color: Color(0xffffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    subtitle1: TextStyle(color: Color(0xffffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    bodyText1: TextStyle(color: Color(0xffffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    bodyText2: TextStyle(color: Color(0xffffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    caption: TextStyle(color: Color(0xb3ffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    button: TextStyle(color: Color(0xffffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    subtitle2: TextStyle(color: Color(0xffffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    overline: TextStyle(color: Color(0xffffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
  ),
  primaryTextTheme: const TextTheme(
    headline1: TextStyle(color: Color(0xb3ffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    headline2: TextStyle(color: Color(0xb3ffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    headline3: TextStyle(color: Color(0xb3ffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    headline4: TextStyle(color: Color(0xb3ffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    headline5: TextStyle(color: Color(0xffffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    headline6: TextStyle(color: Color(0xffffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    subtitle1: TextStyle(color: Color(0xffffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    bodyText1: TextStyle(color: Color(0xffffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    bodyText2: TextStyle(color: Color(0xffffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    caption: TextStyle(color: Color(0xb3ffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    button: TextStyle(color: Color(0xffffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    subtitle2: TextStyle(color: Color(0xffffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    overline: TextStyle(color: Color(0xffffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
  ),
  inputDecorationTheme: InputDecorationTheme(
    labelStyle: const TextStyle(color: Color(0xffffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    helperStyle: const TextStyle(color: Color(0xffffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    hintStyle: const TextStyle(color: Color(0xffffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    errorStyle: const TextStyle(color: Color(0xffffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    errorMaxLines: null,
    isDense: false,
    contentPadding: const EdgeInsets.only(top: 12, bottom: 12, left: 12, right: 12),
    isCollapsed: false,
    prefixStyle: const TextStyle(color: Color(0xffffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    suffixStyle: const TextStyle(color: Color(0xffffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    counterStyle: const TextStyle(color: Color(0xffffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    filled: true,
    fillColor: const Color(0x1affffff),
    floatingLabelBehavior: FloatingLabelBehavior.auto,
    errorBorder: OutlineInputBorder(
      borderRadius: BorderRadius.circular(30),
      borderSide: const BorderSide(width: 1, color: Colors.black, style: BorderStyle.solid),
    ),
    focusedBorder: OutlineInputBorder(
      borderRadius: BorderRadius.circular(30),
      borderSide: const BorderSide(width: 1, color: Colors.black, style: BorderStyle.solid),
    ),
    focusedErrorBorder: OutlineInputBorder(
      borderRadius: BorderRadius.circular(30),
      borderSide: const BorderSide(width: 1, color: Colors.black, style: BorderStyle.solid),
    ),
    disabledBorder: OutlineInputBorder(
      borderRadius: BorderRadius.circular(30),
      borderSide: const BorderSide(width: 1, color: Colors.black, style: BorderStyle.solid),
    ),
    enabledBorder: OutlineInputBorder(
      borderRadius: BorderRadius.circular(30),
      borderSide: const BorderSide(width: 1, color: Colors.black, style: BorderStyle.solid),
    ),
    border: OutlineInputBorder(
      borderRadius: BorderRadius.circular(30),
      borderSide: const BorderSide(width: 1, color: Colors.black, style: BorderStyle.solid),
    ),
  ),
  iconTheme: const IconThemeData(color: Color(0xffffffff), opacity: 1, size: 20),
  primaryIconTheme: const IconThemeData(color: Color(0xffffffff), opacity: 1, size: 20),
  sliderTheme: const SliderThemeData(
    activeTrackColor: null,
    inactiveTrackColor: null,
    disabledActiveTrackColor: null,
    disabledInactiveTrackColor: null,
    activeTickMarkColor: null,
    inactiveTickMarkColor: null,
    disabledActiveTickMarkColor: null,
    disabledInactiveTickMarkColor: null,
    thumbColor: null,
    disabledThumbColor: null,
    thumbShape: null,
    overlayColor: null,
    valueIndicatorColor: null,
    valueIndicatorShape: null,
    showValueIndicator: null,
    valueIndicatorTextStyle: TextStyle(color: Color(0xdd000000), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
  ),
  tabBarTheme: const TabBarTheme(
    indicatorSize: TabBarIndicatorSize.label,
    labelColor: Color(0xffc53a3a),
    unselectedLabelColor: Color(0xff676767),
  ),
  chipTheme: const ChipThemeData(
    backgroundColor: Color(0x1fffffff),
    brightness: Brightness.dark,
    deleteIconColor: Color(0xdeffffff),
    disabledColor: Color(0x0cffffff),
    labelPadding: EdgeInsets.only(top: 0, bottom: 0, left: 8, right: 8),
    labelStyle: TextStyle(color: Color(0xdeffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    padding: EdgeInsets.only(top: 4, bottom: 4, left: 4, right: 4),
    secondaryLabelStyle: TextStyle(color: Color(0x3dffffff), fontSize: null, fontWeight: FontWeight.w400, fontStyle: FontStyle.normal),
    secondarySelectedColor: Color(0x3d212121),
    selectedColor: Color(0x3dffffff),
    shape: StadiumBorder(
        side: BorderSide(
      color: Color(0xff000000),
      width: 0,
      style: BorderStyle.none,
    )),
  ),
  dialogTheme: const DialogTheme(
      shape: RoundedRectangleBorder(
    side: BorderSide(
      color: Color(0xff000000),
      width: 0,
      style: BorderStyle.none,
    ),
    borderRadius: BorderRadius.all(Radius.circular(0.0)),
  )),
  textSelectionTheme: const TextSelectionThemeData(
    cursorColor: Color(0xfffe0000),
    selectionColor: Color(0x40ff0000),
    selectionHandleColor: Color(0x40ff6260),
  ),
);
